### ISSUE TITLE
Error when using keyword

### ISSUE THREAD

**Issue by mohcow** [Garulf/Emoji-plus#10]
After using the plugin's keyword i get following error:

```
Flow Launcher version: 1.9.1
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 01/27/2022 09:39:10
Exception:
System.IO.InvalidDataException: Emoji+|Traceback (most recent call last):
  File "C:\Users\nokz\AppData\Roaming\FlowLauncher\Plugins\Emoji+-1.4.1\run.py", line 12, in <module>
    Emoji()
  File "C:\Users\nokz\AppData\Roaming\FlowLauncher\Plugins\Emoji+-1.4.1\lib\flox\__init__.py", line 107, in __init__
    super().__init__(self.api)
  File "C:\Users\nokz\AppData\Roaming\FlowLauncher\Plugins\Emoji+-1.4.1\lib\flox\launcher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\nokz\AppData\Roaming\FlowLauncher\Plugins\Emoji+-1.4.1\lib\flox\__init__.py", line 113, in _query
    self.query(query)
  File "C:\Users\nokz\AppData\Roaming\FlowLauncher\Plugins\Emoji+-1.4.1\plugin\emoji.py", line 64, in query
    self._results = cache(self.results)(query)
  File "C:\Users\nokz\AppData\Roaming\FlowLauncher\Plugins\Emoji+-1.4.1\lib\flox\utils.py", line 26, in wrapper
    return json.load(f)
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 473901 (char 473900)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 323
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
[2022-01-27.txt](https://github.com/Garulf/Emoji-plus/files/7948938/2022-01-27.txt)

**Comment by Garulf** [comment]
To speed up showing 3000+ emoji this plugin uses a caching method. Looks like your cache file somehow got malformed/corrupted. 

The new caching should be much smarter and know how to handle bad caches.

**Comment by Garulf** [comment]
Thank you for being this to my attention. 

It should be fixed in the latest release. Please update you plugin.

**Comment by mohcow** [comment]
I updated to the lasted release. Issue is still present. Error log below:

```
Flow Launcher version: 1.9.1
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 01/27/2022 20:32:08
Exception:
System.IO.InvalidDataException: Emoji+|Exception ignored in: <function Launcher.__del__ at 0x0000021E95075A60>
Traceback (most recent call last):
  File "C:\Users\nokz\AppData\Roaming\FlowLauncher\Plugins\Emoji+-1.4.2\lib\flox\launcher.py", line 59, in __del__
    self.__call__()
  File "C:\Users\nokz\AppData\Roaming\FlowLauncher\Plugins\Emoji+-1.4.2\lib\flox\__init__.py", line 96, in __call__
    return super().__call__()
  File "C:\Users\nokz\AppData\Roaming\FlowLauncher\Plugins\Emoji+-1.4.2\lib\flox\launcher.py", line 41, in __call__
    results = request_method(*request_parameters)
  File "C:\Users\nokz\AppData\Roaming\FlowLauncher\Plugins\Emoji+-1.4.2\lib\flox\__init__.py", line 127, in _query
    self.query(query)
  File "C:\Users\nokz\AppData\Roaming\FlowLauncher\Plugins\Emoji+-1.4.2\plugin\emoji.py", line 64, in query
    self._results = cache(self.results)(query)
  File "C:\Users\nokz\AppData\Roaming\FlowLauncher\Plugins\Emoji+-1.4.2\lib\flox\utils.py", line 34, in wrapper
    os.remove(cache_file)
NameError: name 'os' is not defined

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 613
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Garulf** [comment]
Sorry about that. I had neglected to add a line in testing to the release version. I'll have this fixed in a moment.
